name: tappayflutterplugin
description: This is a Flutter plugin that help developer to use Tappay Direct Pay.
version: 0.0.7
homepage: https://github.com/TungWang/tappay_flutter_plugin
repository: https://github.com/TungWang/tappay_flutter_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tungwang.tappayflutterplugin
        pluginClass: TappayflutterpluginPlugin
      ios:
        pluginClass: TappayflutterpluginPlugin
